version: "2"

services:
  tcp_server:
    build: tcp_server/
    command: /app
    depends_on:
      - postgres
    ports:
      - "20163:20163"
    networks:
      - postgres

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge